version: '3'
services:
    django: 
      build: ./
      volumes:
      - ./:/usr/src/cook-with-me/
      command: >
        bash -c 
        "
        sh setup_mysql.sh;
        python3 /usr/src/cook-with-me/server/cook_with_me/manage.py runserver 0.0.0.0:8000
        "
      ports:
      - 8888:8000 


      # 
      # 
      # python3 /usr/src/cook-with-me/server/cook_with_me/manage.py runserver 0.0.0.0:8000