version: '3'
services:
  mysql_db:
    image: mysql:8
    restart: always
    environment: 
      - MYSQL_DATABASE=cook_with_me
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes 
      - MYSQL_HOST_CACHE_SIZE=0
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "3306:3306"

  orm_django: 
    build: .
    restart: always
    volumes:
      - ./:/usr/src/app
    command: bash -c 
        "
        python3 /usr/src/app/server/manage.py migrate && 
        python3 /usr/src/app/server/manage.py createsuperuser_on_docker &&
        python3 /usr/src/app/server/manage.py runserver 0.0.0.0:8000 
        "
    depends_on: 
      - mysql_db
    ports:
      - "8000:8000"
   
