# Generated by Django 4.2 on 2023-08-04 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_instruction_recipeingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='servings',
            new_name='serves',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='image',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='instr_order',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='total_time',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe',
        ),
        migrations.AddField(
            model_name='instruction',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instruction',
            name='step_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='note',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='step_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='recipe',
            name='banner_image_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='cookbook.image'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='url_slug',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='metric',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='RecipeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=128)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='instruction',
            name='recipe_component',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cookbook.recipecomponent'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='cookbook.category'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe_component',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cookbook.recipecomponent'),
        ),
    ]
