# Generated by Django 4.2 on 2023-08-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_category_rename_servings_recipe_serves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecomponent',
            name='type',
            field=models.CharField(default='', max_length=128),
        ),
    ]
