# Generated by Django 4.2 on 2023-08-21 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_recipecomponent_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='is_image',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='banner_image_id',
        ),
        migrations.AddField(
            model_name='instruction',
            name='image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cookbook.image'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cookbook.image'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_link',
            field=models.TextField(default=''),
        ),
    ]
