# Generated by Django 4.2 on 2023-08-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.TextField(),
        ),
    ]
