# Generated by Django 4.2 on 2023-08-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0009_alter_instruction_image_alter_recipe_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='source_link',
            field=models.TextField(default='', null=True),
        ),
    ]
