# Generated by Django 4.2 on 2023-09-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0011_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_published',
        ),
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.CharField(default='Unpublished', max_length=128),
        ),
    ]
