# Generated by Django 4.2 on 2023-10-01 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0013_metric_alter_recipe_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='metric',
            new_name='metric_back_up',
        ),
        migrations.AddField(
            model_name='instruction',
            name='recipe_instructional_component',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cookbook.recipeinstructionalcomponent'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe_ingredient_component',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cookbook.recipeingredientcomponent'),
        ),
    ]
