# Generated by Django 4.2 on 2023-10-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0015_recipeingredient_metric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='recipe_component',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='metric_back_up',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe_component',
        ),
        migrations.DeleteModel(
            name='RecipeComponent',
        ),
    ]
