# Generated by Django 4.2 on 2023-10-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0016_remove_instruction_recipe_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.TextField(default='', null=True),
        ),
    ]
