# Generated by Django 4.2 on 2023-10-05 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0018_cuisine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cuisine',
            new_name='cuisine_backup',
        ),
    ]
