# Generated by Django 4.2 on 2023-10-05 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0019_rename_cuisine_recipe_cuisine_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='cookbook.cuisine'),
        ),
    ]
