# Generated by Django 4.2 on 2023-10-05 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0020_recipe_cuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cuisine_backup',
        ),
    ]
