# Generated by Django 4.2 on 2023-10-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0021_remove_recipe_cuisine_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_time',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
